version: 2.1
orbs:
  maven: circleci/maven@1.3.0
  aws-ecr: circleci/aws-ecr@8.1.2
jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#openjdk
      - image: circleci/openjdk:11.0-jdk-buster
    working_directory: ~/oli33-account-service
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - oli33-account-service-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
            paths:
              - ~/.m2
            key: oli33-account-service-{{ checksum "pom.xml" }}
      # package into a jar
      - run: mvn clean package
      - persist_to_workspace:
        root: ./
        paths:
          - target/
workflows:
  version: 2
  build_and_push_image:
    jobs:
      - build
      - aws-ecr/build-and-push-image:
          repo: 'oli33-account-service'
          tag: "${CIRCLE_BRANCH}_${CIRCLE_SHA1},${CIRCLE_BRANCH}_latest"
          requires:
            - build
          workspace-root: ~/oli33-account-service
          attach-workspace: true
          public-registry: false
          push-image: false